jobs:
- job: Main
  steps:
  - checkout: self
    clean: true
    lfs: false

  #Fixes gitversion task
  - bash: |
     shopt -s nullglob
     function join_by { local IFS="$1"; shift; echo "$*"; }
     lib_path=$(join_by ';' $(Agent.WorkFolder)/_tasks/GitVersion*/4.0.*/lib/osx)
     echo LD_LIBRARY_PATH: $lib_path
     echo "##vso[task.setvariable variable=LD_LIBRARY_PATH]$lib_path"

  - task: gittools.gitversion.gitversion-task.GitVersion@4

  - task: NuGetToolInstaller@0

  - task: NuGetCommand@2
    inputs:
      solution: "Stripe.iOS.sln"

  - task: MSBuild@1
    inputs:
      solution: Naxam.Stripe.iOS/Naxam.Stripe.iOS.csproj
      msbuildLocationMethod: version
      msbuildVersion: latest
      msbuildArchitecture: x86
      msbuildArguments: /p:OutputPath=$(Build.SourcesDirectory)/Naxam.Stripe.iOS/bin/Release/ /p:AllowUnsafeBlocks=true
      clean: false
      maximumCpuCount: true
      restoreNugetPackages: false
      logProjectEvents: false
      createLogFile: false
      platform: 'Any CPU'
      configuration: Release

  - task: NuGetCommand@2
    inputs:
      majorVersion: $(GitVersion.Major)
      minorVersion: $(GitVersion.Minor)
      patchVersion: $(GitVersion.Patch)
      command: pack
      packagesToPack: stripe.nuspec

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: $(build.definitionname)
      ArtifactType: "Container"